name: ee-tools
channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh
  - earthengine-api
  - gdal
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pytest
  - python=3.7
  - requests
  - scikit-learn
  - scipy
